import reactLogo from "../img/react.svg";
import domino from "../img/zdj.jpg";
import { GrFormView } from "react-icons/gr";
import { FaComments } from "react-icons/fa";
import { FaHeart } from "react-icons/fa";

const FilmList = [
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 1234,
    img_dm: FaComments,
    dm: 567,
    img_likes: FaHeart,
    likes: 3456,
    title: "Cisza nad Krawędzią",
    creator: "Anna Nowak",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 2345,
    img_dm: FaComments,
    dm: 678,
    img_likes: FaHeart,
    likes: 4567,
    title: "Miasto Snów",
    creator: "Jan Kowalski",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 3456,
    img_dm: FaComments,
    dm: 789,
    img_likes: FaHeart,
    likes: 5678,
    title: "Echo Przeszłości",
    creator: "Magda Wiśniewska",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 4567,
    img_dm: FaComments,
    dm: 890,
    img_likes: FaHeart,
    likes: 6789,
    title: "Cienie Północy",
    creator: "Tomasz Zieliński",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 5678,
    img_dm: FaComments,
    dm: 901,
    img_likes: FaHeart,
    likes: 7890,
    title: "Sekretna Przełęcz",
    creator: "Katarzyna Maj",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 6789,
    img_dm: FaComments,
    dm: 1012,
    img_likes: FaHeart,
    likes: 8901,
    title: "Przebudzenie Lodu",
    creator: "Marek Szymański",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 7890,
    img_dm: FaComments,
    dm: 2123,
    img_likes: FaHeart,
    likes: 9012,
    title: "Tajemnice Lasu",
    creator: "Agnieszka Dąbrowska",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 8901,
    img_dm: FaComments,
    dm: 5234,
    img_likes: FaHeart,
    likes: 1234,
    title: "Droga do Domu",
    creator: "Piotr Kaczmarek",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 9012,
    img_dm: FaComments,
    dm: 2345,
    img_likes: FaHeart,
    likes: 2345,
    title: "Zagubione Światło",
    creator: "Zofia Wójcik",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 10123,
    img_dm: FaComments,
    dm: 1156,
    img_likes: FaHeart,
    likes: 3456,
    title: "Ostatnia Granica",
    creator: "Jakub Lewandowski",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 11234,
    img_dm: FaComments,
    dm: 1467,
    img_likes: FaHeart,
    likes: 4567,
    title: "Zimowy Płomień",
    creator: "Ewa Król",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 12345,
    img_dm: FaComments,
    dm: 3678,
    img_likes: FaHeart,
    likes: 5678,
    title: "Bez Powrotu",
    creator: "Kamil Nowicki",
  },
  {
    id: crypto.randomUUID(),
    img: reactLogo,
    bg: domino,
    img_vive: GrFormView,
    vive: 13456,
    img_dm: FaComments,
    dm: 2789,
    img_likes: FaHeart,
    likes: 6789,
    title: "Nieznane Lądy",
    creator: "Paulina Górska",
  },
];

export default FilmList;
